"""initial schema

Revision ID: ff14c3b9b1d4
Revises: 
Create Date: 2026-04-25 15:44:54.170011

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff14c3b9b1d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Enum('gutenberg', 'open_library', 'standard_ebooks', 'librivox', 'comic_book_plus', 'doab', 'author_upload', 'user_private', name='sourceenum'), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('file_format', sa.Enum('epub', 'pdf', 'txt', 'cbz', name='fileformatenum'), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('license', sa.Enum('public_domain', 'cc_by', 'cc_by_sa', 'cc0', 'author_license', 'user_private', name='licenseenum'), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('visibility', sa.Enum('public', 'private', name='visibilityenum'), server_default='public', nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_books_source_source_id')
    )
    op.create_index('ix_books_created_at', 'books', ['created_at'], unique=False)
    op.create_index('ix_books_visibility_language', 'books', ['visibility', 'language'], unique=False)
    op.create_table('book_subjects',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'subject')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('current_location', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('percent_complete', sa.Float(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_progress')
    op.drop_table('bookmarks')
    op.drop_table('book_subjects')
    op.drop_index('ix_books_visibility_language', table_name='books')
    op.drop_index('ix_books_created_at', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
